---
# Source: fluentd/templates/forwarder-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: elastic-fluentd-forwarder
  labels:
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-4.4.3
    app.kubernetes.io/instance: elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: forwarder
    app: forwarder
spec:
  type: ClusterIP
  ports:
    - name: http
      
      port: 9880
      protocol: TCP
      targetPort: http
  selector: 
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: elastic
    app.kubernetes.io/component: forwarder
