---
# Source: fluentd/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-fluentd-forwarder
  labels:
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-4.4.3
    app.kubernetes.io/instance: elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: forwarder
