---

kind: Namespace
apiVersion: v1
metadata:
  name: elastic
  labels:
    name: elastic
    env: production

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master
  namespace: elastic
  labels:
    env: production
    release: "elasticv1"
    app: "elasticsearch-master"
  annotations:
    {}
spec:
  type: ClusterIP
  selector:
    release: "elasticv1"
    app: "elasticsearch-master"
  publishNotReadyAddresses: false
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
    
---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master-headless
  namespace: elastic
  labels:
    release: "elasticv1"
    app: "elasticsearch-master"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: "elasticsearch-master"
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
