---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: elastic
data:
  zone.sh: |
    ZONE=$(curl -s "http://169.254.169.254/latest/meta-data/placement/availability-zone");
    export ZONE;