---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch
    cluster.initial_master_nodes:
      - elasticsearch-master-0
      - elasticsearch-master-1
      - elasticsearch-master-2
    cluster.routing.allocation.awareness.attributes: zone
    node.name: ${HOSTNAME}
    node.attr.zone: ${ZONE}
    network.host: 0.0.0.0
    discovery.seed_hosts: elasticsearch-master-headless
    discovery.zen.minimum_master_nodes: 2
    path.data: /usr/share/elasticsearch/data