---
name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main          # triggers on pushes that contain changes in main

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        continue-on-error: true # this is just for formatting checking, not a hard fail
        uses: ibiqlik/action-yamllint@v3
